/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v8.0
processor: MIMXRT1062xxxxA
package_id: MIMXRT1062DVL6A
mcu_data: ksdk2_0
processor_version: 8.0.3
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: d6e84094-ad11-42b4-8ad2-e6e1cd911694
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * TEMPMON initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TEMPMON'
- type: 'tempmon'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'tempmon_c966e400757748d37785414258f2801c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TEMPMON'
- config_sets:
  - fsl_tempmon:
    - tempmon_config:
      - singleMeasurement: 'false'
      - clock_config:
        - clockSource: 'LowFreqClock'
        - clockSourceFreq: 'BOARD_BootClockRUN'
      - frequencySet: '1s'
      - lowAlarmTemp: '40'
      - highAlarmTemp: '70'
      - panicAlarmTemp: '90'
    - startMeasure: 'true'
    - interruptsCfg:
      - isInterruptEnabledLowHigh: 'false'
      - interruptLowHigh:
        - IRQn: 'TEMP_LOW_HIGH_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'true'
        - priority: '0'
        - enable_custom_name: 'false'
      - isInterruptEnabledPanic: 'false'
      - interruptPanic:
        - IRQn: 'TEMP_PANIC_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'true'
        - priority: '1'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const tempmon_config_t TEMPMON_config = {
  .frequency = 32768,
  .lowAlarmTemp = 40UL,
  .highAlarmTemp = 70UL,
  .panicAlarmTemp = 90UL
};

static void TEMPMON_init(void) {
  /* TEMPMON initialization */
  TEMPMON_Init(TEMPMON_PERIPHERAL, &TEMPMON_config);
  /* Start measure */
  TEMPMON_StartMeasure(TEMPMON_PERIPHERAL);
}

/***********************************************************************************************************************
 * TRNG initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TRNG'
- type: 'TRNG'
- mode: 'General'
- custom_name_enabled: 'false'
- type_id: 'trng_dd5b2a6f14d45ca091cf6c9a38560d5e'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TRNG'
- config_sets:
  - fsl_trng:
    - settings_trng_config_t:
      - clockMode: 'kTRNG_ClockModeRingOscillator'
      - struct_ring_oscillator:
        - ringOscDiv: 'kTRNG_RingOscDiv0'
        - sampleMode: 'kTRNG_SampleModeRaw'
      - entropyDelay: '3200'
      - sampleSize: '2500'
      - sparseBitLimit: '63'
      - retryCount: '1'
      - lock: 'false'
      - struct_statistical_checks:
        - longRunMaxLimit: '34'
        - monobitLimit:
          - maximum: '1384'
          - minimum: '1116'
        - runBit1Limit:
          - maximum: '405'
          - minimum: '227'
        - runBit2Limit:
          - maximum: '220'
          - minimum: '98'
        - runBit3Limit:
          - maximum: '125'
          - minimum: '37'
        - runBit4Limit:
          - maximum: '75'
          - minimum: '11'
        - runBit5Limit:
          - maximum: '47'
          - minimum: '1'
        - runBit6PlusLimit:
          - maximum: '47'
          - minimum: '1'
        - pokerLimit:
          - maximum: '26912'
          - minimum: '24445'
        - frequencyCountLimit:
          - maximum: '25600'
          - minimum: '1600'
    - quick_selection: 'Default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const trng_config_t TRNG_config = {
  .lock = false,
  .clockMode = kTRNG_ClockModeRingOscillator,
  .ringOscDiv = kTRNG_RingOscDiv0,
  .sampleMode = kTRNG_SampleModeRaw,
  .entropyDelay = 3200,
  .sampleSize = 2500,
  .sparseBitLimit = 63,
  .retryCount = 1,
  .longRunMaxLimit = 34U,
  .monobitLimit = {
    .maximum = 1384UL,
    .minimum = 1116UL
  },
  .runBit1Limit = {
    .maximum = 405UL,
    .minimum = 227UL
  },
  .runBit2Limit = {
    .maximum = 220UL,
    .minimum = 98UL
  },
  .runBit3Limit = {
    .maximum = 125UL,
    .minimum = 37UL
  },
  .runBit4Limit = {
    .maximum = 75UL,
    .minimum = 11UL
  },
  .runBit5Limit = {
    .maximum = 47UL,
    .minimum = 1UL
  },
  .runBit6PlusLimit = {
    .maximum = 47UL,
    .minimum = 1UL
  },
  .pokerLimit = {
    .maximum = 26912UL,
    .minimum = 24445UL
  },
  .frequencyCountLimit = {
    .maximum = 25600UL,
    .minimum = 1600UL
  }
};

static void TRNG_init(void) {
  /* Initialize TRNG. */
  TRNG_Init(TRNG_PERIPHERAL, &TRNG_config);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  TEMPMON_init();
  TRNG_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
